defaults:
  flags:
    file:
      - ".env"
      - "go.mod"
      - "CONTRIBUTING.md"
      - "README.md"
    files:
      - "*.go"
      - "!/sandbox*.*"
      - "!/sandbox/**/*"
      - "!/TODOs.md"
      - "!.env*.local"
